// <auto-generated />
using System;
using DSW1_T2_SermenoCruzMarcos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DSW1_T2_SermenoCruzMarcos.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DSW1_T2_SermenoCruzMarcos.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Gabriel García Márquez",
                            CreatedAt = new DateTime(2025, 12, 10, 2, 46, 35, 252, DateTimeKind.Local).AddTicks(9266),
                            ISBN = "978-0307474728",
                            Stock = 5,
                            Title = "Cien años de soledad"
                        },
                        new
                        {
                            Id = 2,
                            Author = "J.R.R. Tolkien",
                            CreatedAt = new DateTime(2025, 12, 10, 2, 46, 35, 252, DateTimeKind.Local).AddTicks(9283),
                            ISBN = "978-0618260234",
                            Stock = 10,
                            Title = "El Señor de los Anillos"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Gabriel García Márquez",
                            CreatedAt = new DateTime(2025, 12, 10, 2, 46, 35, 252, DateTimeKind.Local).AddTicks(9284),
                            ISBN = "978-0307474729",
                            Stock = 2,
                            Title = "Crónica de una muerte anunciada"
                        });
                });

            modelBuilder.Entity("DSW1_T2_SermenoCruzMarcos.Domain.Entities.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LoanDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            CreatedAt = new DateTime(2025, 12, 5, 2, 46, 35, 252, DateTimeKind.Local).AddTicks(9410),
                            LoanDate = new DateTime(2025, 12, 5, 2, 46, 35, 252, DateTimeKind.Local).AddTicks(9402),
                            Status = "Active",
                            StudentName = "Marcos Cruz"
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            CreatedAt = new DateTime(2025, 11, 30, 2, 46, 35, 252, DateTimeKind.Local).AddTicks(9415),
                            LoanDate = new DateTime(2025, 11, 30, 2, 46, 35, 252, DateTimeKind.Local).AddTicks(9411),
                            ReturnDate = new DateTime(2025, 12, 2, 2, 46, 35, 252, DateTimeKind.Local).AddTicks(9411),
                            Status = "Returned",
                            StudentName = "Ana Gutiérrez"
                        });
                });

            modelBuilder.Entity("DSW1_T2_SermenoCruzMarcos.Domain.Entities.Loan", b =>
                {
                    b.HasOne("DSW1_T2_SermenoCruzMarcos.Domain.Entities.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("DSW1_T2_SermenoCruzMarcos.Domain.Entities.Book", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
